---
title: "Exploring China's Belt and Road Initiative Through Visualizations"
author: "Bethany Dickinson"
date: "9/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE)
```
source: <https://www.aiddata.org/data/chinese-global-official-finance-dataset>

```{r, include = TRUE}

library(tidyverse)
BRI <- read_csv("GlobalChineseOfficialFinanceDataset_v1.0.csv")

```

# Visualization #1 - Africa
```{r Africa}

Africa <- BRI %>%
  select(year, recipient_region, usd_current) %>%
  filter(recipient_region == "Africa") %>%
  arrange(year) %>%
  select(year, usd_current)

Africa_Avg <- Africa %>%
  group_by(year) %>%
  summarize(usd_current = mean(usd_current, na.rm =TRUE)) %>%
  mutate(usd_current_avg = usd_current/1000000)

Africa_Avg %>%
  ggplot() +
  geom_point(aes(x = year, y = usd_current_avg), color = "green", size = 3) +
  geom_smooth(aes(x = year, y = usd_current_avg)) +
  scale_x_continuous(breaks = seq(2000, 2014, by = 1)) +
  scale_y_continuous(breaks = seq(30, 300, by = 50)) +
  theme(axis.text.x = element_text (face = "bold", size = 10, angle = 45))

#need help with scaling appropriately#
```



## Visualization #2 - Asia
```{r Asia}

Asia <- BRI %>%
  select(year, recipient_region, usd_current) %>%
  filter(recipient_region == "Asia") %>%
  arrange(year) %>%
  select(year, usd_current)

Asia_Avg <- Asia %>%
  group_by(year) %>%
  summarize(usd_current = mean(usd_current, na.rm =TRUE)) %>% 
  mutate(usd_current_avg = usd_current/1000000)


ggplot(Asia_Avg, aes(year, usd_current_avg)) +
  geom_col(aes(fill = usd_current_avg, position = "dodge")) +
  geom_text(aes(label = usd_current_avg), position = position_dodge(0.1)) +
  scale_x_continuous(breaks = seq(2000, 2014, by = 1)) +
  scale_y_continuous(breaks = seq(20, 500, by = 50)) +
  theme(axis.text.x = element_text (face = "bold", size = 10, angle = 45))

```




## Visualization #3 - The Middle East
```{r The Middle East}

Middle_East <- BRI %>% 
  select(year, recipient_region, usd_current) %>%
  filter(recipient_region == "Middle East") %>%
  arrange(year) %>%
  select(year, usd_current)


```


## Visualization #4 - The Pacific 

```{r The Pacific Region}

The_Pacific <- BRI %>%
  select(year, recipient_region, usd_current) %>%
  filter(recipient_region == "The Pacific") %>%
  arrange(year) %>%
  select(year, usd_current) 

The_Pacific_Avg <- The_Pacific %>%
  group_by(year) %>%
  summarize(usd_current = sum(usd_current, na.rm =TRUE)) %>%
  mutate(usd_current2 = usd_current/10000) 

The_Pacific_Avg %>%
  ggplot() +
  geom_point(aes(x = year, y = usd_current2), color = "blue", shape = "triangle") +
  geom_smooth(aes(x = year, y = usd_current2)) +
  scale_x_continuous(breaks = seq(2000, 2014, by = 1)) +
  scale_y_continuous(breaks = seq(700, 77000, by = 7000)) +
  theme(axis.text.x = element_text (face = "bold", size = 10, angle = 45))

#how to scale this accurately#
```


